[book]
authors = ["RM"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence"
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
[output.html]
mathjax-support = true


